// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbx_KRjYQG3-XME7kpXKwxenNv62gZu8m2tLYl4ibomxW3jaFXjGRHdTOhHGvsNq_Z65/exec";
